version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  
  bookstore:
    image: bookstore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      TZ: "Asia/Saigon"